name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Node"
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "18.x"
      - name: "Fetch deployment script"
        uses: actions/checkout@v2
        with:
          repository: Team-Radiateur/bot-auto-deploy
      - name: "Run script"
        env:
          PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
          PTERODACTYL_API_URL: ${{ secrets.PTERODACTYL_API_URL }}
          PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }}
        run: node src/index.js
